### ISSUE TITLE
Naming of Maps API Key

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretix-passbook#17]
The plugin has a setting to provide an API-Key for the geocoding-Feature.

https://github.com/pretix/pretix-passbook/blob/7f5e285671e02aa19da3420f17cb348fadd9433a/pretix_passbook/signals.py#L56-L61

I would like to reuse it in the Google Pay Passes plugin. While setting up the API-key for myself, I realized that calling the setting "Google Maps API key" might be confusing, as in reality we need a Key for the Geocoding API.

Should we perhaps change the label to "Google Geocoding API key"? The Google API-console is a little confusing at times, as it they call the API "Geocoding API", but sometimes show a Google Maps-Icon next to it.

Please let me know what you think - I would then piggyback on that decision and setting ;-)

**Comment by raphaelm** [comment]
Agreed!
