### ISSUE TITLE
Question: Passbook Setup 

### ISSUE THREAD

**Issue by kc9ryt** [pretix/pretix-passbook#21]
Could someone point me in the right direction on how to setup passbook? I have generated my certificate signing request and gone into the apple developer program and generated a certificate. I have then uploaded the certificate to pretix. I have uploaded the apple CA certificate. Then for the secret key, I cannot get it to accept the private key that is included with the apple certificate.

**Comment by raphaelm** [comment]
The secret key is something you generate together with your CSR, like
```
openssl genrsa -out pass-pretix.key 2048
```

You should be able to paste this file in there. Do you get any error message?

**Comment by kc9ryt** [comment]
I was following Apples guide on creating the CSR so that was my problem. Thanks!
