### ISSUE TITLE
Passbook not working

### ISSUE THREAD

**Issue by gleichaberanders** [pretix/pretix-passbook#25]
Hey together,

i just followed the official documentation to implement passbook ticketing.
I also created the keys with
openssl genrsa -out pass-pretix.key 2048 / openssl req -new -key pass-pretix.key -out pass-pretix.csr

<img width="923" alt="Bildschirmfoto 2019-03-18 um 19 50 15" src="https://user-images.githubusercontent.com/48489114/54561133-33069d80-49c4-11e9-992b-7b30580d18fe.png">

I could download the .pkpass files but I am not able to open them with any iOS Device. 
I just attached the generated preview ( pkpass files not allowed, just created a zip file)
[ticket-preview.pkpass.zip](https://github.com/pretix/pretix-passbook/files/2980116/ticket-preview.pkpass.zip)

**Comment by raphaelm** [comment]
Hi,

I'm not sure if something else is wrong, but at least the "Passbook-Typ" is wrong, this needs to be the typestring you registered with apple (e.g. de.gleichaberanders.ticket etc).

Best
Raphael

**Comment by gleichaberanders** [comment]
Hey, yeah you're right, that was my failure... 
Just the first time ever used an Apple DEV Account / Passbook, thank you very much!
