### ISSUE TITLE
Error while loading suggested geolocations

### ISSUE THREAD

**Issue by DottoreTozzi** [pretix/pretix-passbook#27]
Thanks for this nice plugin!
It's working fine here so far, but I can't seem to be able to enter the geolocations in the correct format, I'm always getting the above error...

**Comment by pc-coholic** [comment]
This message is displayed, when the automatic geocoding using the Google Maps Geocoding API has failed.

Please enable Admin-Mode on your pretix instance, head to the Global Settings and save a Geocoding API-Key.

That should fix the issue.

**Comment by DottoreTozzi** [comment]
Thank you!
Turns out, my API Key wasn't activated... 
Stupid mistake on my side.

It'd be nice, however, if the above error message was a little bit clearer on this.
