### ISSUE TITLE
Font colors chosen incorrectly

### ISSUE THREAD

**Issue by DottoreTozzi** [pretix/pretix-passbook#31]
I had set the background for the passbook/wallet tickets to a light blueish color png.
Unfortunately, this sets the font color of event and product details, as well as the dates, to white, which is unreadable.
The header font color is set to black (in this case, correctly).
In the preview, all is well, all fonts black, but the actual wallet item shows white color.

**Comment by raphaelm** [comment]
By preview, do you mean our preview download or the preview on the iOS device? Can you post a screenshot?

(It feels like a bug in iOS, though)

**Comment by DottoreTozzi** [comment]
The preview download from pretix looked ok, all black fonts.

This is what it looks like in iOS:
https://cloud.heimbrauconvention.de/s/PgoeGHK8ZBo236e

And this is how it looks on Android:
https://cloud.heimbrauconvention.de/s/cJP5TASDEEbjMXM

I've cleared the background to default white and now it's OK, but I'm looking forward to a better solution.... ;)
Our Ticket Shop is in full swing right now, so I don't want to change any settings again for the time being...

**Comment by raphaelm** [comment]
Hmm. Well, in theory the app should automatically choose the font color. If we would add a setting for the font color, we would put that burden on the user, but could prevent such situations. I'm not really sure what's the best solution here.

**Comment by wiffbi** [comment]
The automatic coloring obviously does not work that well. #51 adds manual options to tweak colors.
