### ISSUE TITLE
Apple Wallet support broken?

### ISSUE THREAD

**Issue by DottoreTozzi** [pretix/pretix-passbook#43]
We are currently using pretix 4.2.0, passbook-tickets 1.9.0.
On Android mobile devices everything works fine, but on iOS (iPhone), an error message is displayed:
"Safari cannot download this file".
Any help regarding this issue would be highly appreciated...

**Comment by raphaelm** [comment]
Have you checked that your Passbook Certificate is up to date? Can you share one of the broken files?

**Comment by DottoreTozzi** [comment]
OK, thank you, it is very likely that the certificate has expired.
I'll close this for now.

**Comment by DottoreTozzi** [comment]
I have created a new certificate and followed all the steps in the readme (?) but unfortunately I still get the same error message. There isn't any broken file, as the download doesn't even begin.
How can I further debug this? Team ID and passbook type should be correct.

**Comment by DottoreTozzi** [comment]
Sorry, false alarm, without further ado it suddenly works.

**Comment by DottoreTozzi** [comment]
Sorry for reopening this.
For this year's event, I've failed to check the certificates on time, and stupidly ran into this problem again.
I've updated the certificate, and for all orders from that moment onwards, the passes are working.
However, all those who ordered before then have invalid passes.
Is there a way to get pretix to update them?

**Comment by raphaelm** [comment]
pretix only caches passes for a few hours, so they should automatically be regenerated next time they are downloaded
