### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Dragonstyl444** [pretix/pretix-passbook#46]
hey i uploaded the csr into the global settings but this bug still persists, i can't Preview the Passbook.

Can anyone help
![11](https://user-images.githubusercontent.com/105603781/186518557-1e37e856-98c8-490a-85c7-5e14a9b3bf8d.png)
![Unbenannt](https://user-images.githubusercontent.com/105603781/186518559-2959abdc-b83e-40ee-b482-f265ce638fe2.png)

**Comment by pc-coholic** [comment]
You also need to fill out the passbook Passbook team Id, type and organizer name.

When you generated the CSR and uploaded it to Apple, they did ask you for your passbook type and did provide you with a TeamID.
