### ISSUE TITLE
Ability to hide the ticket code

### ISSUE THREAD

**Issue by fabm3n** [pretix/pretix-passbook#49]
Currently, the ticket code is displayed on the ticket below the QR-Code:
![image](https://user-images.githubusercontent.com/11352551/205265881-1711e3a7-bb93-4d5e-a00e-46c1e7871299.png)

It would be nice if the ticket code could be hidden from the ticket.

**Comment by raphaelm** [comment]
No, sorry, this likely won't happen.

1. The code may be useful in situations that can hardly be predicted
2. We won't introduce options for small details like this, as the gain is little and every single additional option makes pretix harder to configure (and maintain)

see also discussion in #32

**Comment by fabm3n** [comment]
Thanks for the information. I didn't find #32 before.
