### ISSUE TITLE
Passbook global settings not visible

### ISSUE THREAD

**Issue by Eskolo** [pretix/pretix-passbook#72]
I enabled the plugin and I can enable the passbook ticket type in ticket settings but the general settings (To set the team id etc.) are not there. It seems that the `register_global_settings` in `signals.py` is not called by pretix? 

Do i have to enable anything so the settings will show up?

**Comment by raphaelm** [comment]
Can't reproduce, it's showing up on all my installations

**Comment by Eskolo** [comment]
Hm.. Am I correct that the settings should show up under 'Event Settings > General'? Is there another way of configuring the passbook plugin, like in the configuration file? If yes how would that look like?

**Comment by raphaelm** [comment]
No, they show up in the "global settings" on system level, only visible jn admin mode. They are not per-event

**Comment by Eskolo** [comment]
Yeah that was it.. Thanks! sorry for bothering you with my blindness! Maybe add the location to the readme ^^
